export default [
  [1, 'cost~a -ae f', 'rib / ребро'],
  [1, 'clāvicul~a -ae f', 'collar-bone / ключица'],
  [1, 'foss~a -ae f', 'pit, groove / ямка, углубление'],
  [1, 'glandul~a -ae f', 'gland / железá'],
  [1, 'palpebr~a -ae f', 'eyelid / веко'],
  [1, 'vertebr~a -ae f', 'vertebra / позвонок'],
  [1, 'cyst~a -ae f', 'cyst / киста'],
  [1, 'pneumoni~a -ae f [!pl]', 'pneumonia / пневмония'],
  [1, 'gutt~a -ae f', 'drop / капля'],
  [1, 'herb~a -ae f', 'herb / трава'],

  [2, 'cili~um -ī n', 'eyelash / ресница'],
  [2, 'ligāment~um -ī n', 'ligament / связка'],
  [2, 'ole~um -ī n', 'oil / масло'],
  [2, 'gangli~on -ī n', 'ganglion / ганглий, нервный узел'],
  [2, 'digit~us -ī m', 'finger / палец'],
  [2, 'ocul~us -ī m', 'eye / глаз'],
  [2, 'lob~us -ī m', 'lobe / доля'],
  [2, 'morb~us -ī m', 'disease / болезнь, заболевание'],
  [2, 'can-cer -cr~ī m [!pl]', 'cancer / рак, раковая опухоль'],
  [2, 'morbill~ī -ōrum m [!sg]', 'measles / корь'],

  [4, 'abscess~us -ūs m', 'abscess / абсцесс, гнойник'],
  [4, 'dēcubit~us -ūs m', 'decubitus ulcer / пролежень'],
  [4, 'sin~us -ūs m', 'sinus / пазуха'],
  [4, 'abort~us -ūs m', 'abortion, miscarriage / аборт, выкидыш'],
  [4, 'frūct~us -ūs m', 'fruit / плод'],
  [4, 'part~us -ūs m [!pl]', '(child)birth / роды'],
  [4, 'man~us -ūs f', 'hand / рука'],
  [4, 'Querc~us -ūs f', 'oak / дуб'],
  [4, 'gen~ū -ūs n', 'knee / колено'],
  [4, 'corn~ū -ūs n', 'horn / рог'],

  [5, 'faci~ēs -ēī f', 'face; surface / лицо; поверхность'],
  [5, 'superfici~ēs -ēī f', 'surface / поверхность'],
  [5, 'seri~ēs -ēī f', 'row, series / ряд, серия'],
  [5, 'aci~ēs -ēī f', 'sharp edge / остриё'],
  [5, 'speci~ēs -ēī f', 'species / вид, разновидность'],
  [5, 'māteri~ēs -ēī f [!pl]', 'matter, substance / вещество, материя'],
  [5, 'rabi~ēs -ēī f [!pl]', 'rabies / бешенство'],
  [5, 'scabi~ēs -ēī f [!pl]', 'scabies, itch / чесотка'],
  [5, 'cari~ēs -ēī f [!pl]', 'caries, decay / кариес, гниение'],
  [5, 'r~ēs reī f', 'thing; matter / вещь; дело'],
];
