export default [
  ["X", "<big>X</big>\n\n<b>X, x</b>\n<i>двадцать третья буква латинского алфавита</i>; как обозначение числа = 10; на монетах = denarius (<i>как содержащий 10 ассов</i>); XCCCCC = denariis quadringentis."],
  ["Xanthicus mensis", "<big>Xanthicus mensis</big>\n\n<b>Xanthicus mensis, is</b> <i>m</i>\nксантик, <i>месяц в македонском календаре, прибл. совпадающий с нашим апрелем</i> <i>Eccl</i>."],
  ["Xanthippe", "<big>Xanthippe</big>\n\n<b>Xanthippe, es</b> <i>f</i>\nКсантиппа,] <i>жена Сократа</i> (<i>вошедшая в поговорку своей раздражительностью и сварливостью</i>) <i>C, AG</i>."],
  ["Xanthippus", "<big>Xanthippus</big>\n\n<b>Xanthippus, i</b> <i>m</i>\nКсантипп:\n<b>1)</b> <i>афинянин, отец Перикла, политик и полководец, победитель при Микале</i> (<i>479 г. до н. э.</i>) <i>C</i>;\n<b>2)</b> <i>спартанец, командовавший отрядами наёмников в карфагенской армии во время I Пунической войны, победитель Регула при Тунете (Tunes) в 255 г. до н. э.</i> <i>C, Veg</i>."],
  ["Xantho", "<big>Xantho</big>\n\n<b>Xantho, us</b> <i>f</i>\nКсанто, <i>морская нимфа, дочь Нерея и Дориды</i> <i>V</i>."],
  ["Xanthus", "<big>Xanthus</big>\n\n<b>Xanthus (-os), i</b> <i>m</i> (<i>греч.</i> «золотисто-жёлтый»)\nКсант:\n<b>1)</b> <i>эпитет реки Скамандр в Троаде</i> <i>V, PM</i>;\n<b>2)</b> <i>речка в Эпире</i> <i>V</i>;\n<b>3)</b> <i>река в зап. Ликии</i> <i>V, H, O</i>."],
  ["xeniolum", "<big>xeniolum</big>\n\n<b>xeniolum, i</b> <i>n</i> [<i>demin. к</i> xenium]\nнебольшой подарок гостю <i>Ap, Dig</i>."],
  ["Xenippa", "<big>Xenippa</big>\n\n<b>Xenippa, orum</b> <i>n</i>\nКсениппа, <i>местность в сев.-зап. части Согдианы</i> <i>QC</i>."],
  ["xenium", "<big>xenium</big>\n\n<b>xenium, i</b> <i>n</i> (<i>преим.</i> <i>pl.</i>) (<i>греч.</i>)\n<b>1)</b> ксений, подарок гостю <i>Vtr, PJ, M</i>; подношение, дар <i>Dig, PJ</i>;\n<b>2)</b> <i>pl.</i> <i>название XIII книги эпиграмм Марциала.</i>"],
  ["Xeno", "<big>Xeno</big>\n\n<b>Xeno, onis</b> <i>m</i>\nКсенон, <i>философ-эпикуреец из Афин, современник Цицерона</i> <i>C</i>."],
  ["Xenocles", "<big>Xenocles</big>\n\n<b>Xenocles, is</b> <i>m</i>\nКсенокл, <i>ритор, с которым был близок Цицерон в бытность свою в Малой Азии</i> <i>C</i>."],
  ["Xenocrates", "<big>Xenocrates</big>\n\n<b>Xenocrates, is</b> <i>m</i>\nКсенократ, <i>родом из Халкедона, греч. философ, ученик Платона; после Спевсиппа возглавлял афинскую Академию</i> (<i>396-314 гг. до н. э.</i>) <i>C</i>."],
  ["xenodochium", "<big>xenodochium</big>\n\n<b>xenodochium (-eum), i</b> <i>n</i> (<i>греч.</i>)\nстранноприимный дом (и госпиталь) <i>CJ, Hier</i>."],
  ["xenodochus", "<big>xenodochus</big>\n\n<b>xenodochus, i</b> <i>m</i> (<i>греч.</i>)\nзаведующий странноприимным домом <i>CJ</i>."],
  ["xenon", "<big>xenon</big>\n\n<b>xenon, onis</b> <i>m</i> <i>CJ</i>\n= xenodochium."],
  ["xenoparochus", "<big>xenoparochus</big>\n\n<b>xenoparochus, i</b> <i>m</i> <i>Dig</i>\n= parochus."],
  ["Xenophanes", "<big>Xenophanes</big>\n\n<b>Xenophanes, is</b> <i>m</i>\nКсенофан, <i>родом из Колофона, греч. философ, основатель элейской филос. школы (2-я половина VI в. до н. э.</i>) <i>C</i>."],
  ["Xenophon", "<big>Xenophon</big>\n\n<b>Xenophon, ontis</b> <i>m</i>\nКсенофонт, <i>родился в Афинах ок. 444 г. до н. э., греч. историк, военачальник и публицист, ученик Сократа; руководил отступлением 10000 греков после битвы при Кунаксе (401 г. до н. э.), которое описал в «Анабасисе»; умер в Коринфе в 354 г. до н. э.; его основные произведения: «Anabasis», «Cyropaedia», «Apomnemoneumata», «Memorabilia»</i> <i>Vr, C, Nep, Sen</i>."],
  ["Xenophonteus", "<big>Xenophonteus</big>\n\n<b>Xenophonteus (-ius), a, um</b> [Xenophon]\nксенофонтов (genus sermonis <i>C</i>)."],
  ["xerampelinae", "<big>xerampelinae</big>\n\n<b>xerampelinae, arum</b> <i>f</i> (<i>греч.</i>)\n(<i>sc.</i> vestes) тёмно-красная одежда цвета сухих виноградных листьев <i>J</i>."],
  ["xerophagi", "<big>xerophagi</big>\n\n<b>xerophagi, orum</b> <i>m</i> (<i>греч.</i>; <i>sc.</i> panes)\nсухие пирожки, сухари <i>Pt</i> (<i>v. l.</i>)."],
  ["xerophagia", "<big>xerophagia</big>\n\n<b>xerophagia, ae</b> <i>f</i> (<i>греч.</i>)\nсухоедение <i>Tert</i>."],
  ["xerophthalmia", "<big>xerophthalmia</big>\n\n<b>xerophthalmia, ae</b> <i>f</i> (<i>греч.</i>; <i>лат.</i> arida lippitudo)\nсухое гнойное воспаление глаз <i>CC</i>."],
  ["Xerxes", "<big>Xerxes</big>\n\n<b>Xerxes (Xerses), is</b> (<i>acc.</i> en) <i>m</i>\nКсеркс, <i>царь Персии в 485-465 гг. до н. э., сын и преемник пария Гистаспа; в войне против Греции потерпел поражение при Соломине (480 г. до н. э.) и Платеях (479 г. до н. э.); убит в 465 г. до н. э.</i> <i>Vr, C, Nep</i>."],
  ["xiphias", "<big>xiphias</big>\n\n<b>xiphias, ae</b> <i>m</i> (<i>греч.</i>; <i>лат.</i> gladius)\n<b>1)</b> меч-рыба <i>PM, O</i>;\n<b>2)</b> мечевидная комета <i>PM</i>."],
  ["xiphium", "<big>xiphium</big>\n\n<b>xiphium (-on), i</b> <i>n</i> (<i>греч.</i>; <i>лат.</i> gladiolus) <i>бот.</i>\nгладиолус, шпажник <i>PM</i>."],
  ["xylinus", "<big>xylinus</big>\n\n<b>xylinus, a, um</b> (<i>греч.</i>)\nдревесный, <i>перен.</i> хлопковый: lina xylina <i>PM</i> хлопчатобумажная ткань."],
  ["xylobalsamum", "<big>xylobalsamum</big>\n\n<b>xylobalsamum, i</b> <i>n</i>\nбальзамное дерево <i>PM</i>."],
  ["xylocassia", "<big>xylocassia</big>\n\n<b>xylocas(s)ia, ae</b> <i>f</i> (<i>греч.</i>)\nдревесина кассии <i>Dig</i>."],
  ["xylocinnamomum", "<big>xylocinnamomum</big>\n\n<b>xylocinnamomum, i</b> <i>n</i>\nкоричное дерево <i>PM, Dig</i>."],
  ["xylocinnamum", "<big>xylocinnamum</big>\n\n<b>xylocinnamum, i</b> <i>n</i> <i>Scr</i>\n= xylocinnamomum."],
  ["xylon", "<big>xylon</big>\n\n<b>xylon, i</b> <i>n</i> (<i>греч.</i>)\nхлопчатник <i>PM</i>."],
  ["Xyniae", "<big>Xyniae</big>\n\n<b>Xyniae, arum</b> <i>f</i>\nКсинии, <i>город в юго-зап. Фессалии, на реке Xynias</i> <i>L</i>."],
  ["xyris", "<big>xyris</big>\n\n<b>xyris, idis</b> (<i>acc.</i> im) <i>f</i> (<i>греч.</i>)\nдикий ирис <i>PM</i>."],
  ["xystarcha", "<big>xystarcha</big>\n\n<b>xystarcha (-es), ae</b> <i>m</i> [xystus 1]\nксистарх, заведующий ксистом <i>Amm, Tert</i>."],
  ["xystici", "<big>xystici</big>\n\n<b>xystici, orum</b> <i>m</i> [xystus I]\nксистики, <i>атлеты, состязающиеся в ксисте</i> <i>Su, Dig</i>."],
  ["xysticus", "<big>xysticus</big>\n\n<b>xysticus, a, um</b> [xystus I]\nспортивный (vanitas <i>Tert</i>)."],
  ["xystum", "<big>xystum</big>\n\n<b>xystum, i</b> <i>n</i> <i>v. l.</i>\n= xystus 2."],
  ["xystus", "<big>xystus</big>\n\n<b>xystus, i</b> <i>m</i> (<i>греч.</i>)\nксист:\n<b>1)</b> <i>у греков — крытая колоннада (в гимнасиях) для зимних занятий атлетов</i> <i>Vtr, Tert</i>;\n<b>2)</b> (<i>тж.</i> xystum, i <i>n</i>) <i>у римлян — открытая терраса для прогулок в загородных постройках</i> <i>C, Sen, PJ, Ph</i>."]
]