export default [
  ["Z", "<big>Z</big>\n\n<b>Z, z</b>\nдвадцать пятая буква латинского алфавита (употр. преим. в словах греч. происхождения)."],
  ["zabolus", "<big>zabolus</big>\n\n<b>zabolus (zabulus), i</b> <i>m</i> <i>Eccl</i>\n= diabolus."],
  ["Zacynthius", "<big>Zacynthius</big>\n\n<b>Zacynthius, a, um</b> [Zacynthus]\nзакинфский (Calchas <i>Pl</i>)."],
  ["Zacynthus", "<big>Zacynthus</big>\n\n<b>Zacynthus (-os), i</b> <i>f</i>\nЗакинф, <i>о-в в Ионическом море, к зап. от Пелопоннеса</i> (<i>ныне</i> Занте); <i>по преданию, метрополия испанского Сагунта</i> <i>L, V, O etc.</i>"],
  ["zaeta", "<big>zaeta</big>\n\n<b>zaeta</b> <i>v. l.</i>\n= diaeta."],
  ["Zaleucus", "<big>Zaleucus</big>\n\n<b>Zaleucus, i</b> <i>m</i>\nЗалевк, <i>законодатель в Локрах Эпизефирийских (южн. Италия) (VII в. до н. э.</i>) <i>C, Sen</i>."],
  ["Zalmoxis", "<big>Zalmoxis</big>\n\n<b>Zalmoxis</b> <i>v. l.</i>\n= Zamolxis."],
  ["Zama", "<big>Zama</big>\n\n<b>Zama, ae</b> <i>f</i>\nЗама, <i>укреплённый город в южн. Зевгитане (Нумидия), к юго-зап. от Карфагена, резиденция царя Юбы (ныне</i> Zowarin); <i>здесь в 202 г. до н. э. Сципион нанёс поражение Ганнибалу</i> <i>Sl, bAfr, L</i>."],
  ["Zamensis", "<big>Zamensis</big>\n\n<b>Zamensis, is</b> <i>m</i>\nжитель города Зама <i>bAfr</i>."],
  ["zamia", "<big>zamia</big>\n\n<b>zamia, ae</b> <i>f</i> (<i>греч.</i>)\nущерб, убыток, потеря <i>Pl</i>."],
  ["Zamolxis", "<big>Zamolxis</big>\n\n<b>Zamolxis</b> <i>и</i> <b>Zalmoxis, is</b> <i>m</i>\nЗалмоксис, <i>философ-пифагореец из Фракии</i> <i>Ap</i>."],
  ["zanca", "<big>zanca</big>\n\n<b>zanca (tzanga), ae</b> <i>f</i>\nпарфянская обувь <i>Treb, CTh</i>."],
  ["Zanclaeus", "<big>Zanclaeus</big>\n\n<b>Zanclaeus, a, um</b> <i>O</i>\n= Zancleius."],
  ["Zancle", "<big>Zancle</big>\n\n<b>Zancle, es</b> <i>f</i>\nЗанкла, <i>древнее название города Messana</i> (<i>в сев.-вост. Сицилии</i>) <i>O, Sil</i>."],
  ["Zancleius", "<big>Zancleius</big>\n\n<b>Zancleius, a, um</b> [Zancle]\nзанклейский (saxa <i>O</i>): Zancleia moenia <i>Sil</i> = Messana."],
  ["zaplutus", "<big>zaplutus</big>\n\n<b>z&#257;pl&#363;tus, a, um</b> (<i>греч.</i>)\nочень богатый <i>Pt</i>."],
  ["zea", "<big>zea</big>\n\n<b>zea, ae</b> <i>f</i> (<i>греч.</i>)\nполба <i>или</i> пшеница-двузернянка (<i>Triticum Spelta</i>, L.) <i>PM</i>."],
  ["Zela", "<big>Zela</big>\n\n<b>Zela, ae</b> <i>f</i>\nЗела, <i>укреплённый пункт в зап. Понте, к югу от Амасеи; место победы Митридата над Т. Триарием в 67 г. и поражения Фарнака Ю. Цезарем в 47 г. до н. э.</i> <i>bAl, PM</i>."],
  ["zelator", "<big>zelator</big>\n\n<b>zelator, oris</b> <i>m</i> [zelo(r)]\nревнитель <i>Ambr</i>."],
  ["zelivira", "<big>zelivira</big>\n\n<b>zeli–vira, ae</b> <i>f</i> [vir] <i>Tert</i>\n= zelotypa."],
  ["zelo", "<big>zelo</big>\n\n<b>zelo, avi, atum, are</b>, <i>чаще</i> <b>zelor, atus sum, ari</b> (<i>греч.</i>)\n<b>1)</b> горячо любить (populum summo pietatis amore <i>Tert</i>);\n<b>2)</b> возревновать (zelo zelatus sum pro domino deo exercituum <i>Vlg</i>)."],
  ["zelotes", "<big>zelotes</big>\n\n<b>zelotes, ae</b> <i>m</i> (<i>греч.</i>)\nзилот, ревнитель <i>Vlg, Eccl</i>."],
  ["zelotypa", "<big>zelotypa</big>\n\n<b>zelotypa, ae</b> <i>f</i> (<i>греч.</i>)\nревнивица <i>Pt</i>."],
  ["zelotypia", "<big>zelotypia</big>\n\n<b>zelotypia, ae</b> <i>f</i> (<i>греч.</i>)\nревность <i>PM, Vlg</i>."],
  ["zelotypus 1", "<big>zelotypus</big>\n\n<b>I zelotypus, a, um</b> (<i>греч.</i>)\nревнивый, завистливый (mulier <i>Vlg</i>; homo <i>J</i>)."],
  ["zelotypus 2", "<big>zelotypus</big>\n\n<b>II zelotypus, i</b> <i>m</i>\nревнивец, завистник <i>Q, M, Pt, Aus</i>."],
  ["zelus", "<big>zelus</big>\n\n<b>zelus, i</b> <i>m</i> (<i>греч.</i>) <i>Vtr, Eccl, Aus</i>\n= zelotypia."],
  ["Zenobia", "<big>Zenobia</big>\n\n<b>Zenobia, ae</b> <i>f</i>\nЗенобия (Зиновия):\n<b>1)</b> <i>дочь царя Митридата Армянского</i> <i>T</i>;\n<b>2)</b> <i>жена Одената, царя Пальмирского, по его смерти — царица Пальмиры; потерпела поражение от римск. войск Аврелиана</i> (<i>273 г. н. э.</i>) <i>Treb, Vop, Eutr</i>."],
  ["Zenon", "<big>Zenon</big>\n\n<b>Zenon</b> <i>и</i> <b>Zeno, onis</b> <i>m</i>\nЗенон:\n<b>1)</b> <i>родом из Элей (южн. Италия) (ок. 460 г. до н. э.), ученик Парменида, представитель элейской филос. школы, учитель Перикла</i> <i>C</i>;\n<b>2)</b> <i>родом из Кития (Кипр), основатель стоической филос. школы в Афинах (III-II вв. до н. э.</i>) <i>Vr, C, Sen</i>;\n<b>3)</b> <i>философ-эпикуреец, учитель Цицерона и Аттика</i> <i>C</i>."],
  ["Zephyritis", "<big>Zephyritis</big>\n\n<b>Zephyritis, idis</b> <i>f</i>\nЗефиритида, <i>прозвище Арсинои, жены Птолемея Филадельфа</i> <i>Ctl</i>."],
  ["Zephyrium", "<big>Zephyrium</big>\n\n<b>Zephyrium, i</b> <i>n</i>\nЗефирий:\n<b>1)</b> <i>мыс в Бруттии, юго-зап. оконечность Апеннинского п-ова</i> <i>Mela, PM</i>;\n<b>2)</b> <i>мыс в Киликии, к вост. от Soli</i> <i>L, PM</i>."],
  ["zephyrius", "<big>zephyrius</big>\n\n<b>zephyrius, a, um</b> [zephyrus]:\nzephyria ova (<i>или</i> ova urina) <i>PM</i> яйца без зародыша, &laquo;болтуны&raquo;."],
  ["zephyrus", "<big>zephyrus</big>\n\n<b>zephyrus, i</b> <i>m</i> (<i>греч.</i>; <i>лат.</i> Favonius)\nзефир, западный весенний ветер <i>H, PM, Sen etc.</i>; <i>поэт.</i> ветер (<i>вообще</i>) <i>V</i>."],
  ["Zerynthius", "<big>Zerynthius</big>\n\n<b>Zerynthius, a, um</b> [Zerynthus]\nзеринфский (litora <i>O</i>)."],
  ["Zerynthus", "<big>Zerynthus</big>\n\n<b>Zerynthus, i</b> <i>f</i>\nЗеринф, <i>город во Фракии</i> (<i>с пещерой Гекаты</i>) <i>L</i>."],
  ["zeta 1", "<big>zeta</big>\n\n<b>I z&#275;ta</b> <i>indecl. n</i>\nзета, <i>название греч. буквы</i> &Zeta;, &zeta;, <i>Aus</i>."],
  ["zeta 2", "<big>zeta</big>\n\n<b>II zeta, ae</b> <i>f</i> <i>Lampr</i>\n= diaeta 2."],
  ["zetematium", "<big>zetematium</big>\n\n<b>zetematium, i</b> <i>n</i> (<i>греч.</i>)\nмаленькое исследование, изысканьице <i>LM</i>."],
  ["Zetes", "<big>Zetes</big>\n\n<b>Zetes, ae</b> <i>m</i>\nЗет, <i>крылатый сын Борея и Орифии (Orithyia), брат Калаиса, участник похода Аргонавтов</i> <i>O, Prp</i>."],
  ["Zethus", "<big>Zethus</big>\n\n<b>Zethus, i</b> <i>m</i>\nЗеф, <i>сын Юпитера и Антиопы, брат-близнец Амфиона, основатель города Фивы</i> <i>C, H</i>."],
  ["Zetus", "<big>Zetus</big>\n\n<b>Zetus, i</b> <i>m</i>\nЗет, <i>известный математик</i> <i>Sid</i>."],
  ["Zeugitana regio", "<big>Zeugitana regio</big>\n\n<b>Zeugitana regio</b>\n<i>местность в Африке</i> (<i>сев. часть современного Туниса</i>) <i>PM</i>."],
  ["zeugma 1", "<big>zeugma</big>\n\n<b>I zeugma, atis</b> <i>n</i> (<i>греч.</i>; <i>лат.</i> ligatio <i>или</i> annexio)\nзевгма, <i>грам. фигура, состоящая в подчинении одному члену предложения ряда других, из которых по смыслу лишь один может быть ему подчинён, напр.</i>: lex poenaque lata <i>H</i> (<i>вместо</i> lex lata poenaque irrogata)."],
  ["Zeugma 2", "<big>Zeugma</big>\n\n<b>II Zeugma, atis</b> <i>n</i>\nЗевгма, <i>город в Сирии, на правом берегу Евфрата</i> (<i>ныне</i> Zima) <i>PM, T, St, Lcn</i>."],
  ["Zeuxis", "<big>Zeuxis</big>\n\n<b>Zeuxis, idis</b> (<i>acc.</i> im, in <i>и</i> idem) <i>m</i>\nЗевксид, <i>родом из Гераклеи (южн. Италия), греч. живописец II-й половины <i>V</i> в. до н. э.</i> <i>C, PM, Pt</i>."],
  ["zingiber", "<big>zingiber</big>\n\n<b>zingiber, eris</b> <i>n</i> (<i>греч.</i>)\nимбирь <i>CC, Pall</i>."],
  ["zingiberi", "<big>zingiberi</big>\n\n<b>zingiberi, eris</b> <i>n</i> <i>PM, Dig</i>\n= zingiber."],
  ["zizania 1", "<big>zizania</big>\n\n<b>I zizania, orum</b> <i>n</i> (<i>греч.</i>)\nплевел(ы) <i>Vlg, Eccl</i>."],
  ["zizania 2", "<big>zizania</big>\n\n<b>II zizania, ae</b> <i>f</i> <i>Aug</i>\n= zizania I."],
  ["zizyphum", "<big>zizyphum</big>\n\n<b>zizyphum, i</b> <i>n</i>\nплод дерева zizyphus <i>PM</i>."],
  ["zizyphus", "<big>zizyphus</big>\n\n<b>zizyphus, i</b> <i>m</i> (<i>греч.</i>)\n<i>дерево</i> ююба (<i>Rhamnus jujuba</i>, L. <i>или</i> <i>Zizyphus vulgaris</i>) <i>Col, PM, Pall</i>."],
  ["zmaragdus", "<big>zmaragdus</big>\n\n<b>zmaragdus, i</b> <i>m, f</i> <i>v. l.</i>\n= smaragdus."],
  ["Zmyrna", "<big>Zmyrna</big>\n\n<b>Zmyrna, ae</b> <i>f</i> <i>v. l.</i>\n= Smyrna II."],
  ["zmyrus", "<big>zmyrus</big>\n\n<b>zmyrus, i</b> <i>m</i>\nсамец мурены <i>PM</i>."],
  ["zodiacus 1", "<big>zodiacus</big>\n\n<b>I zodiacus, i</b> <i>m</i> (<i>греч.</i>; <i>лат.</i> orbis signifer)\nзодиак <i>C, AG, Cens</i>."],
  ["zodiacus 2", "<big>zodiacus</big>\n\n<b>II zodiacus, a, um</b>\nзодиакальный (diastema <i>Sid</i>)."],
  ["zodium", "<big>zodium</big>\n\n<b>zodium, i</b> <i>n</i> (<i>греч.</i>)\nсозвездие зодиака <i>Cens</i>."],
  ["Zoilus", "<big>Zoilus</big>\n\n<b>Zoilus, i</b> <i>m</i>\nЗоил:\n<b>1)</b> <i>греч. ритор и грамматик в Александрии (середина III в. до н. э.), мелочный критик Гомера</i> <i>Vtr</i>;\n<b>2)</b> <i>перен.</i> придирчивый, недоброжелательный критик <i>O, M</i>."],
  ["zona", "<big>zona</big>\n\n<b>zona, ae</b> <i>f</i> (<i>греч.</i>; <i>лат.</i> cingulum)\n<b>1)</b> женский пояс (<i>как символ девственности</i>) (zonam solvere <i>Ctl</i> <i>или</i> recingere <i>O</i>);\n<b>2)</b> пояс для денег, (у мужчин) поясной кошелёк (argentum in zonis habere <i>L</i>);\n<b>3)</b> ободок драгоценного камня <i>PM</i>;\n<b>4)</b> пояс Ориона <i>O</i>;\n<b>5)</b> климатический пояс, зона <i>V, O etc.</i>: z. nivalis <i>Lcn</i> ледовитый (холодный) пояс; z. perusta <i>Lcn</i> жаркий пояс;\n<b>6)</b> <i>Scr</i> = zoster I, 1;\n<b>7)</b> кайма <i>или</i> оторочка одежды <i>Is</i>."],
  ["zonalis", "<big>zonalis</big>\n\n<b>zonalis, e</b> [zona 5]\nзональный, поясной (ambitus<i>Macr</i>)."],
  ["zonarius 1", "<big>zonarius</big>\n\n<b>I zonarius, a, um</b> [zona 2]\nпоясной: z. sector <i>Pl</i> срезыватель кошельков, карманный вор."],
  ["zonarius 2", "<big>zonarius</big>\n\n<b>II zonarius, i</b> <i>m</i> [zona 2]\nзонарий, <i>мастер, делающий пояса</i> <i>LM, C</i>."],
  ["zonatim", "<big>zonatim</big>\n\n<b>zonatim</b> [zona]\nкругом, вокруг, в виде кольца (claudere <i>LM</i>)."],
  ["zonula", "<big>zonula</big>\n\n<b>zonula, ae</b> <i>f</i> [<i>demin. к</i> zona 2]\nпоясок <i>Ctl, Lampr</i>."],
  ["zophorus", "<big>zophorus</big>\n\n<b>zophorus, i</b> <i>m</i> (<i>греч.</i>)\nфриз колонны <i>Vtr</i>."],
  ["zopissa", "<big>zopissa</big>\n\n<b>zopissa, ae</b> <i>f</i>\nсгустки смоляной обмазки кораблей, корабельная смола <i>PM</i>."],
  ["Zopyriatim", "<big>Zopyriatim</big>\n\n<b>Zopyriatim</b> <i>adv.</i> [Zopyrus]\nпо примеру Зопира <i>LM</i>."],
  ["Zopyrus", "<big>Zopyrus</big>\n\n<b>Zopyrus, i</b> <i>m</i>\nЗопир:\n<b>1)</b> <i>знатный перс, изувечивший себя и содействовавший этим завоеванию Вавилона Дарием</i> <i>Just</i>;\n<b>2)</b> <i>физиогномист, современник Сократа</i> <i>C</i>."],
  ["Zoroastres", "<big>Zoroastres</big>\n\n<b>Zoroastres, is</b> <i>m</i>\nЗороастр (Зердушт), <i>религиозный реформатор, восстановитель древнеиранской религии</i> (<i>рубеж II <i>и</i> I тысячелетий до н. э.</i>) <i>Just, PM, Sol, Ap</i>."],
  ["Zoroastreus", "<big>Zoroastreus</big>\n\n<b>Zoroastreus, a, um</b>\nзороастров, <i>перен.</i> чародейский (susurri <i>Eccl</i>)."],
  ["zoster 1", "<big>zoster</big>\n\n<b>I zoster, eris</b> <i>m</i> (<i>греч.</i>)\n<b>1)</b> пояс, <i>перен. мед.</i> опоясывающий антонов огонь <i>или</i> рожа <i>PM</i>;\n<b>2)</b> морская водоросль <i>PM</i>."],
  ["Zoster 2", "<big>Zoster</big>\n\n<b>II Zoster, eris</b> <i>m</i>\nЗостер, <i>мыс и портовый город на юго-зап. побережье Аттики</i> <i>C</i>."],
  ["zotheca", "<big>zotheca</big>\n\n<b>zotheca, ae</b> <i>f</i> (<i>греч.</i>)\nкомната для отдыха, кабинет <i>PJ</i>."],
  ["zothecula", "<big>zothecula</big>\n\n<b>zothecula, ae</b> <i>f</i> [<i>demin. к</i> zotheca]\nкабинетик <i>PJ, Sid</i>."],
  ["zuma", "<big>zuma</big>\n\n<b>zuma, ae</b> <i>f</i> (<i>греч.</i>)\n<b>1)</b> котелок <i>или</i> кастрюля <i>Treb</i>;\n<b>2)</b> отвар, бульон <i>Is</i>."],
  ["zygia 1", "<big>zygia</big>\n\n<b>I zygia, ae</b>\n<b>1.</b> <i>f</i> граб (<i>дерево</i>) <i>PM</i>;\n<b>2.</b> <i>adj. f</i>: z. tibia <i>Ap</i> свадебная флейта."],
  ["Zygia 2", "<big>Zygia</big>\n\n<b>II Zygia, ae</b> <i>f</i> (<i>греч.</i> &laquo;устраивающая брак&raquo;)\n<i>эпитет Юноны</i> <i>Ap</i>."],
  ["zygostasium", "<big>zygostasium</big>\n\n<b>zygostasium, i</b> <i>n</i> (<i>греч.</i>)\nпроверка веса <i>CJ</i>."],
  ["zygostata", "<big>zygostata</big>\n\n<b>zygostata (-es), ae</b> <i>m</i> (<i>греч.</i>)\nвесовщик <i>CJ</i>."],
  ["zythum", "<big>zythum</big>\n\n<b>zythum, i</b> <i>n</i>\nячменная брага (<i>у египтян</i>) <i>Col, PM</i>."]
]