export default [
  [1, 'am~āre', 'love / любить'],
  [1, 'clām~āre', 'cry, shout / кричать'],
  [1, 'rog~āre', 'ask / спрашивать'],
  [1, 'lev~āre', 'elevate / поднимать, повышать'],
  [1, 'iter~āre', 'repeat / повторять'],
  [1, 'aedific~āre', 'build / строить'],
  [1, 'voc~āre', 'call / звать'],
  [1, 'cant~āre', 'sing / петь'],
  [1, 'numer~āre', 'count / считать'],
  [1, 'salūt~āre', 'greet / приветствовать'],

  [2, 'vid~eō vīd~ī vīs~um -ēre', 'see / видеть'],
  [2, 'respond~eō respond~ī respōns~um -ēre', 'answer / отвечать'],
  [2, 'hab~ēre', 'have / иметь'],
  [2, 'ten~eō -u~ī tent~um -ēre', 'hold / держать'],
  [2, 'terg~eō ters~ī ters~um -ēre', 'wipe / протирать'],
  [2, 'mov~eō mōv~ī mōt~um -ēre', 'move / двигать'],
  [2, 'torr~eō -u~ī tost~um -ēre', 'dry, parch / сушить, жечь'],
  [2, 'fov~eō fōv~ī fōt~um -ēre', 'keep warm / согревать'],
  [2, 'compl~eō -ēv~ī -ēt~um -ēre', 'fill up / заполнять'],
  [2, 'arc~ēre', 'hold off / (у, с)держивать'],

  [3.1, 'sūm~ō sūmps~ī sūmpt~um -ere', 'take / брать'],
  [3.1, 'ag~ō ēg~ī āct~um -ere', 'do / делать'],
  [3.1, 'veh~ō vex~ī vect~um -ere', 'carry, convey / нести, везти'],
  [3.1, 'vert~ō vers~ī vers~um -ere', 'turn / вертеть, поворачивать'],
  [3.1, 'em~ō ēm~ī ēmpt~um -ere', 'buy / покупать'],
  [3.1, 'dūc~ō dūx~ī duct~um -ere', 'lead / вести'],
  [3.1, 'crēd~ō crēdid~ī -itum -ere', 'believe / верить'],
  [3.1, 'lūd~ō lūs~ī lūs~um -ere', 'play / играть'],
  [3.1, 'toll~ō sustul~ī sublāt~um -ere', 'lift, raise / поднимать'],
  [3.1, 'fall~ō fefell~ī fals~um -ere', 'deceive / обманывать'],

  [3.2, 'fac~iō fēc~ī fact~um -ere', 'make / делать', {
    2: [
      ['fī_ō', 'fī_s', 'fi_t'],
      ['fī_mus', 'fī_tis', 'fī:u_nt'],
    ],
    4: [
      ['fī^ēba_m', 'fī^ēbā_s', 'fī^ēba_t'],
      ['fī^ēbā_mus', 'fī^ēbā_tis', 'fī^ēba_nt'],
    ],
    6: [
      ['fī^a_m', 'fī^ē_s', 'fī^e_t'],
      ['fī^ē_mus', 'fī^ē_tis', 'fī^e_nt'],
    ],
  }],
  [3.2, 'cap~iō cēp~ī capt~um -ere', 'take, take hold of / брать, хватать'],
  [3.2, 'iac~iō iēc~ī iact~um -ere', 'throw / кидать'],
  [3.2, 'a-spic~iō -spex~ī -spect~um -ere', 'look / глядеть'],
  [3.2, 'ac-cip~iō -cēp~ī -cept~um -ere', 'accept / принимать'],
  [3.2, 'inter-fic~iō -fēc~ī -fect~um -ere', 'kill / убивать'],
  [3.2, 'rap~iō -u~ī rapt~um -ere', 'seize; carry off / хватать; похищать'],
  [3.2, 'cōn-fic~iō -fēc~ī -fect~um -ere', 'complete / завершать'],
  [3.2, 'af-fic~iō -fēc~ī -fect~um -ere', 'affect / причинять'],
  [3.2, 'cōn-spic~iō -spex~ī -spect~um -ere', 'get sight of / заметить'],

  [4, 'aud~īre', 'hear; listen / слышать; слушать'],
  [4, 'fīn~īre', 'limit / ограничивать'],
  [4, 'moll~īre', 'soften / размягчать'],
  [4, 'pol~īre', 'polish / полировать'],
  [4, 'lin~īre', 'smear / смазывать'],
  [4, 'pūn~īre', 'punish / наказывать'],
  [4, 'fer~īre', 'strike, smite / ударять, поражать'],
  [4, 'haur~iō haus~ī haust~um -īre', 'draw; drink up / черпать; выпивать'],
  [4, 'sepel~iō -īv~ī sepult~um -īre', 'bury, inter / хоронить, погребать'],
  [4, 'sc~īre', 'know / знать'],
];
