$_GET({
  title: 'Plinius Minor. Epistulae. VI, 16',
  text: `
C. Plīnius Tacitō suō s.

{1}Petis ut tibi avunculī meī [[exitum | =exitus]] scrībam, quō vērius trādere [[posterīs | =posteri]] possīs. Grātiās~agō; nam videō mortī eius, sī [[celebrētur | =celebro]] ā~tē, immortālem glōriam esse [[prōpositam | =propono]]. {2}Quamvīs~enim pulcherrimārum [[clāde | =cladis]] terrārum, ut populī, ut urbēs [[memorābilī | =memorabilis]] [[cāsū | =casus]], [[quasi | =quasi]] semper {{vīctūrus | от *vīvere*}} occiderit; quamvīs ipse plūrima opera et {{mānsūra | i.e. opera mānsūra: *mānsūrus* от *manēre*}} [[condiderit | =condo]] — multum tamen [[perpetuitātī | =perpetuitas]] eius [[scrīptōrum | =scriptum]] tuōrum [[aeternitās | =aeternitas]] addet. {3}[[Equidem | =equidem]] beātōs putō quibus deōrum [[mūnere | =munus]] datum~est aut facere scrībenda aut scrībere legenda, beātissimōs vērō quibus utrumque. Hōrum~in numerō avunculus meus et suīs librīs et tuīs erit. Quō [[libentius | =libenter]] [[suscipiō | =suscipio]], [[dēposcō | =deposco]] etiam quod [[iniungis | =injungo]].

{4}Erat Mīsēnī classemque imperiō [[praesēns | =praesens]] regēbat. Nōnum {{Kal. | Kalendās}} Septembrēs hōrā [[ferē | =fere]] septimā māter mea [[indicat | =indico]] eī [[appārēre | =appareo]] nūbem [[inūsitātam | =inusitatus]] et [[magnitūdine | =magnitudo]] et [[speciē | =species]]. {5}{{Ūsus | ^ppa^ от *ūtī*}} ille sōle, mox [[frīgidā | =frigida]], [[gustāverat | =gusto]] iacēns studēbatque; poscit [[soleās | =solea]], ascendit locum ex quō maximē [[mīrāculum | =miraculum]] illud cōnspicī poterat. Nūbēs (incertum procul intuentibus ex quō monte; Vesuvium fuisse posteā cognitum est) oriēbātur, cuius [[similitūdinem | =similitudo]] et fōrmam nōn alia magis arbor quam [[pīnus | =pinus]] [[expresserit | =exprimo]]. <...> {7}Magnum propiusque {{nōscendum | ^grnd^ от *nōscere*}} ut ērudītissimō virō vīsum. Iubet [[liburnicam | =liburna]] [[aptārī | =apto]]; mihi, sī venīre ūnā vellem, facit [[cōpiam | =copia]]; respondī studēre mē [[mālle | =malo]], et forte ipse quod scrīberem dēderat. {8}Ēgrediēbātur domō; accipit [[cōdicillōs | =codicillus]] Rēctīnae Tascī [[imminentī | =immineo]] perīculō exterritae (nam vīlla eius [[subiacēbat | =subjaceo]], nec ūlla nisi nāvibus fuga): ut sē tantō [[discrīminī | =discrimen]] [[ēriperet | =eripio]] [[ōrābat | =oro]]. {9}Vertit ille cōnsilium et quod studiōsō animō [[incohāverat | =inchoo]] [[obit | =obeo]] maximō. Dēdūcit [[quadrirēmēs | =quadriremis]], ascendit ipse nōn Rēctīnae modo sed multīs (erat enim frequēns [[amoenitās | =amoenitas]] ōrae) lātūrus auxilium. {10}[[Properat | =propero]] illūc unde aliī fugiunt, rēctumque cursum, rēcta [[gubernācula | =gubernaculum]] in [[perīculum | =periculum]] tenet <...>.

{11}Iam nāvibus [[cinis | =cinis]] incidēbat, quō propius accēderent, calidior et [[dēnsior | =densus]]; iam [[pūmicēs | =pumex]] etiam nigrīque et [[ambustī | =ambustus]] et frāctī igne [[lapidēs | =lapis]]; iam [[vadum | =vadum]] subitum ruīnaque montis lītora [[obstantia | =obsto]]. [[Cūnctātus | =cunctor]] paulum an~retrō [[flecteret | =flecto]], mox gubernātōrī ut ita faceret monentī “Fortēs,” inquit, “[[fortūna | =fortuna]] iuvat: Pompōniānum pete.” {12}Stabiīs erat [[dirēmptus | =dirimo]] [[sinū | =sinus]] mediō (nam [[sēnsim | =sensim]] [[circumāctīs | =circumactus]] curvātīsque lītoribus mare [[infunditur | =infundo]]); ibi <...> [[sarcinās | =sarcina]] [[contulerat | =confero]] in nāvēs, certus fugae sī contrārius ventus [[resēdisset | =resido]]. Quō tunc avunculus meus secundissimō invectus, complectitur [[trepidantem | =trepido]], cōnsōlātur, [[hortātur | =hortor]]; utque timōrem eius suā [[sēcūritāte | =securitas]] [[lēnīret | =lenio]], [[dēferrī | =defero]] in [[balineum | =balneum]] iubet; [[lōtus | =lotus]] [[accubat | =accubo]], cēnat, aut [[hilaris | =hilaris]] aut (quod aequē~magnum) [[similis | =similis]] hilarī.

{13}Interim ē Vesuviō~monte plūribus locīs lātissimae [[flammae | =flamma]] altaque [[incendia | =incendium]] [[relūcēbant | =reluceo]], quōrum [[fulgor | =fulgor]] et [[clāritās | =claritas]] [[tenebrīs | =tenebrae]] noctis excitābātur. Ille [[agrestium | =agrestis]] trepidātiōne ignēs relictōs dēsertāsque vīllās per [[sōlitūdinem | =solitudo]] [[ārdēre | =ardeo]] in [[remedium | =remedium]] [[formīdinis | =formido]] [[dictitābat | =dictito]]. Tum sē [[quiētī | =quies]] dedit et [[quiēvit | =quiesco]] vērissimō quidem somnō... {14}<...> Excitātus prōcēdit, sēque Pompōniānō cēterīsque quī [[pervigilāverant | =pervigilo]] reddit. {15}In commūne cōnsultant, intrā tēcta [[subsistant | =subsisto]] an in [[apertō | =apertum]] [[vagentur | =vagor]]. Nam [[crēbrīs | =creber]] vāstīsque [[tremōribus | =tremor]] tēcta [[nūtābant | =nuto]], et quasi [[ēmōta | =emoveo]] [[sēdibus | =sedes]] suīs nunc hūc nunc illūc abīre aut referrī vidēbantur. {16}Sub [[dīō | =dium]] rūrsus quamquam levium exēsōrumque pūmicum cāsus metuēbātur, quod tamen perīculōrum [[collātiō | =collatio]] [[ēlēgit | =eligo]]; et apud illum quidem [[ratiō | =ratio]] ratiōnem, apud aliōs timōrem timor vīcit. [[Cervīcālia | =cervical]] capitibus imposita [[linteīs | =linteum]] [[constringunt | =constringo]]; id [[mūnīmentum | =munimentum]] adversus incidentia fuit.

{17}Iam diēs [[alibī | =alibi]], illīc nox omnibus noctibus nigrior dēnsiorque; quam tamen [[facēs | =fax]] multae variaque [[lūmina | =lumen]] solvēbant. [[Placuit | =placeo]] ēgredī in lītus, et ex~proximō adspicere, [[ecquid | =ecquid]] iam mare [[admitteret | =admitto]]; quod adhūc [[vāstum | =vastus]] et adversum [[permanēbat | =permaneo]]. {18}Ibi super [[abiectum | =abjicio]] linteum [[recubāns | =recubo]] semel atque iterum frīgidam aquam poposcit hausitque. Deinde flammae flammārumque [[praenūntius | =praenuntius]] [[odor | =odor]] [[sulpuris | =sulphur]] aliōs in fugam vertunt, excitant illum. {19}[[Innītēns | =innitor]] [[servolīs | =servulus]] duōbus assurrēxit et statim [[concidit | =concido]], ut ego [[colligō | =colligo]], crassiōre [[cālīgine | =caligo]] [[spīritū | =spiritus]] [[obstructō | =obstruo]], clausōque [[stomachō | =stomachus]] quī illī nātūrā [[invalidus | =invalidus]] et angustus et frequenter [[aestuāns | =aestuo]] erat. {20}Ubi diēs redditus (is ab eo quem [[ | =nove]] vīderat tertius), corpus inventum integrum [[illaesum | =illaesus]] opertumque ut fuerat indūtus: [[habitus | =habitus]] corporis quiēscentī quam [[dēfūnctō | =defunctus]] similior.

{21}Interim Mīsēnī ego et māter —sed nihil ad historiam, nec tū aliud quam dē exitū eius scīre voluistī. Fīnem ergō faciam. {22}Ūnum [[adiciam | =adjicio]]: omnia mē quibus [[interfueram | =intersum]] quaeque statim, cum maximē vēra memorantur, audieram —persecūtum. Tū [[potissima | =potissimus]] [[excerpēs | =excerpo]]: aliud est enim epistulam, aliud historiam; aliud amīcō, aliud omnibus scrībere. Valē.

---

Г. Плиний Тациту своему п<ривет>~<шлет>

Просишь чтобы тебе дяди моего кончину описал чтобы~тем вернее передать потомкам ты~мог Благодарю ибо вижу <что>~смерти его если будет~распространена тобою бессмертная слава — обещана Ибо~↔~хотя прекраснейших в~разрушении земель как народы как города в~памятном происшествии словно вечно собиравшийся~жить пал~(умер)~<он> хотя сам очень~многие труды и то~что~останется сочинил многое однако увековечиванию его произведений твоих бессмертность добавит Я~право счастливыми считаю <тех>~кому богов милостью дано или вершить достойное~описания или писать достойное~чтения наисчастливейшими же <тех>~кому и~то~и~другое Их~↔~в числе дядя мой и своими книгами и твоими будет Отчего охотнее принимаю требую даже <то>~что возлагаешь~<на~меня>

Был~<он> в~Мизене и~флотом командуя лично управлял. В~девятый~<день> <до>~календ сентябрьских часу примерно в~седьмом мать моя указывает ему <что>~появилась туча необыкновенная и величиною и видом Насладившись — солнцем затем холодной~водою он~уже~откушал и~лежа занимался просит сандалии поднимается на~место с которого лучше~всего диковина та рассмотреться могла Туча неясно издали взиравшим из какой горы <что~это>~Везувий был потом признано было поднималась чье подобие и форму никакое иное лучше дерево нежели сосна не~выразило~бы — Значительным и~ближайшего изучения~стоящим как образованнейшему человеку показалось~<это> Велит <чтобы>~либурна была~приготовлена мне если ехать совместно хочу предоставляет возможность <я>~ответил <что>~заниматься я предпочитаю и по~счастливой~случайности <он>~сам что написать задал~<мне> <Он>~выходил из~дому получает записку Ректины <жены>~Тасция нависшей опасностью перепуганной ибо вилла ее находилась~внизу и~не~<было> никакого кроме~как по~морю спасения чтобы ее из~такого опасного~положения спас просила Изменил он план и <то>~что из~любознательного порыва начал совершил из~благородного Спускает квадриремы всходит~<на~борт> сам не Ректине только но многим была ибо многолюдна красота побережья собираясь~оказать помощь Спешит туда откуда другие бегут и~прямой курс прямо <правя>~рулем в опасность держит —

Уж на~корабли пепел падал чем ближе подходили <тем>~горячей и гуще уже пемза даже и~черные и обугленные и разбитые огнем камни уже отмель внезапная и~обвал горы побережье преграждающий Помешкав немного назад~↔~ли не~повернуть вскоре кормчему чтобы так поступить уговаривавшему Смелым мол судьба помогает к~Помпониану правь В~Стабиях <он>~был разделенный заливом посреди ведь постепенно в~извилистые изогнутые берега море вливается там — пожитки снес на корабли решившийся на~бегство если встречный ветер уляжется Куда тогда дядя мой с~попутным приплыв обнимает трепещущего утешает ободряет и~дабы страх его своею беззаботностью унять отвести~себя в баню велит намывшись ложится~<за~стол> обедает или веселый или что равнозначно подобный веселому

Меж~тем из горы~↔~Везувия во~многих местах широчайшие языки~пламени и~высокие пожары вспыхивали чей блеск и яркость мраком ночи раздувались Он <что>~поселян смятением огни оставлены и~<что>~покинутые дома по безлюдью пылают для устранения страха всё~говорил Затем (себя) отдыху отдал(ся) и заснул самым~настоящим право сном — Разбуженный выходит и~(себя) к~Помпониану и~прочим которые не~засыпали возвращает(ся) Для общего~блага совещаются в помещениях оставаться или на открытом~месте бродить Ибо частыми и~мощными встрясками крыши~(дома́) шатались и будто сдвинутые с~мест своих то сюда то туда уходят или возвращаются казалось Под открытым~небом напротив хотя легкой и~размытой пемзы падение было~страшно что впрочем рисков сопоставление выбрало и у того притом довод над~доводом, у других над~страхом страх возобладал Подушки на~головы возложенные простынями стягивают это прикрытие против падающих~<камней> было

Уж день в~другом~месте там ночь всех ночей чернее и~плотнее которую впрочем факелы многочисленные и~разные огни рассеивали Было~угодно выйти на берег и сблизи посмотреть есть~ли теперь к~морю подступ каковое по-прежнему неистовым и враждебным оставалось Тогда на выброшенный парус откинувшись раз и другой холодной воды попросил и~выпил Затем языки~пламени и~пламя возвещающий запах серы других в бегство обращают подымают его Опираясь на~молодых~рабов двух поднялся и тотчас рухнул как я заключаю <ибо>~сгустившимися испарениями дыхание заградило и~перекрыло пищевод который у~него от~природы слабый и узкий и часто горящий~(изжогой) был Как~только день вернулся — от того который последним увидел третий тело <было>~найдено целым невредимым и~покрытым как был~<он> одет облик тела со~спящим нежели с~покойным более~схож~<был>

Меж~тем в~Мизене я и мать но ничего по~отношению~к истории да~и ты не~иначе как о кончине его узнать пожелал Точку посему ставлю Одно добавлю всё я при~чем присутствовал и~что тотчас когда наиболее точное помнится услышал изложил Ты важнейшее извлечешь одно~<дело> — ведь письмо другое историю одно другу другое всем писать Будь~здоров

---

Плиний Тациту привет.

{1}Ты просишь описать тебе гибель моего дяди; хочешь точнее передать о нем будущим поколениям. Благодарю; я знаю, что смерть его будет навеки прославлена, если ты расскажешь о ней людям. {2}Он, правда, умер во время катастрофы, уничтожившей прекрасный край с городами и населением их, и это памятное событие сохранит навсегда и его имя; он сам создал много трудов, но твои бессмертные произведения очень продлят память о нем. {3}Я считаю счастливыми людей, которым боги дали или свершить подвиги, достойные записи, или написать книги, достойные чтения; к самым же счастливым тех, кому даровано и то и другое. В числе их будет и мой дядя — благодаря своим книгам и твоим. Тем охотнее берусь я за твое поручение и даже прошу дать его мне.

{4}Дядя был в Мизене и лично командовал флотом. В девятый день до сентябрьских календ, часов около семи, мать моя показывает ему на облако, необычное по величине и по виду. {5}Дядя уже погрелся на солнце, облился холодной водой, закусил и лежа занимался; он требует сандалии и поднимается на такое место, откуда лучше всего можно было разглядеть это удивительное явление. Облако (глядевшие издали не могли определить, над какой горой оно возникало; что это был Везувий, признали позже), по своей форме больше всего походило на пинию <...>. {7}Явление это показалось дяде, человеку ученому, значительным и заслуживающим ближайшего ознакомления. Он велит приготовить либурнику и предлагает мне, если хочу, ехать вместе с ним. Я ответил, что предпочитаю заниматься; он сам еще раньше дал мне тему для сочинения. {8}Дядя собирался выйти из дому, когда получил письмо от Ректины, жены Тасция: перепуганная нависшей опасностью (вилла ее лежала под горой, и спастись можно было только морем), она просила дядю вывести ее из этого ужасного положения. {9}Он изменил свой план: и то, что предпринял ученый, закончил человек великой души; он велел вывести квадриремы и сам поднялся на корабль, собираясь подать помощь не только Ректине, но и многим другим (это прекрасное побережье было очень заселено). {10}Он спешит туда, откуда другие бегут, держит прямой путь, стремится прямо в опасность <...>.

{11}На суда уже падал пепел, и чем ближе они подъезжали, тем горячее и гуще; уже куски пемзы и черные обожженные обломки камней, уже внезапно отмель и берег, доступ к которому прегражден обвалом. Немного поколебавшись, не повернуть ли назад, как уговаривал кормщик, он говорит ему: «смелым в подмогу судьба: правь к Помпониану». {12}Тот находился в Стабиях, на противоположном берегу (море вдается в землю, образуя постепенно закругляющуюся, искривленную линию берега). <...> Помпониан погрузил на суда свои вещи, уверенный, что отплывет, если стихнет противный ветер. Дядя прибыл с ним: для него он был благоприятнейшим. Он обнимает струсившего, утешает его, уговаривает; желая ослабить его страх своим спокойствием, велит отнести себя в баню; вымывшись, располагается на ложе и обедает — весело или притворяясь веселым — это одинаково высоко.

{13}Тем временем во многих местах из Везувия широко разлился, взметываясь кверху, огонь, особенно яркий в ночной темноте. Дядя твердил, стараясь успокоить перепуганных людей, что селяне впопыхах забыли погасить огонь и в покинутых усадьбах занялся пожар. Затем он отправился на покой и заснул самым настоящим сном... {14}<...> Дядю разбудили, и он присоединился к Помпониану и остальным, уже давно бодрствовавшим. {15}Все советуются, оставаться ли в помещении или выйти на открытое место: от частых и сильных толчков здания шатались; их словно сдвинуло с мест, и они шли туда-сюда и возвращались обратно. {16}Под открытым же небом было страшно от падавших кусков пемзы, хотя легких и пористых; выбрали всё-таки последнее, сравнив одну и другую опасность. У дяди один разумный довод возобладал над другим, у остальных один страх над другим страхом. В защиту от падающих камней кладут на головы подушки и привязывают их полотенцами.

{17}По другим местам день, здесь ночь чернее и плотнее всех ночей, хотя темноту и разгоняли многочисленные факелы и разные огни. Решили выйти на берег и посмотреть вблизи, можно ли выйти в море: оно было по-прежнему бурным и враждебным. {18}Дядя лег на подостланный парус, попросил раз-другой холодной воды и глотнул ее. Огонь и запах серы, возвещающий о приближении огня, обращают других в бегство, а его подымают на ноги. {19}Он встал, опираясь на двух рабов, и тут же упал, думаю, потому что от густых испарений ему перехватило дыхание и закрыло дыхательное горло: оно у него от природы было слабым, узким и часто побаливало. {20}Когда вернулся дневной свет (на третий день после того, который он видел в последний раз), тело его нашли в полной сохранности, одетым как он был; походил он скорее на спящего, чем на умершего.

{21}Тем временем в Мизене мать и я — но это не имеет никакого отношения к истории, да и ты хотел узнать только о его гибели. Поэтому я кончаю. {22}Добавлю одно: я передал всё, при чем присутствовал сам и о чем услыхал почти сразу же, когда хорошо помнят, как всё было. Ты извлечешь главное: одно дело писать письмо, а другое — историю; одно — другу и другое — всем. Будь здоров.
`
});