$_GET({
  title: 'Seneca Minor. Epistulae. I, 1',
  text: `
Seneca Lūcīliō suō salūtem.

Ita fac, mī Lūcīlī: [[vindicā | #*vindicāre*# @1) claim; appropriate / _притязать на, требовать; присваивать_ @2) liberate / _освобождать_]] tē tibi, et tempus, quod adhūc aut auferēbātur aut [[subripiēbātur | #*sur-ripere (sub-)* -iō -uisse -reptum# @steal, take away secretly / _похищать, красть, захватывать тайком_]] aut [[excidēbat | #*ex-cidere* -cidisse# @fall out, fall from, slip out / _(вы, про)падать, (вы, у)скальзывать_]], [[collige | #*col-ligere* -lēgisse -lēctum# @gather, collect, put together / _собирать; скоплять_]] et servā. Persuādē~tibi hoc sīc esse ut scrībō: quaedam tempora [[ēripiuntur | #*ē-ripere* -iō -uisse -reptum# @snatch away / _вырывать, выхватывать, отнимать_]] {{nōbīs | dativus relationis – _дательный отношения: называет лицо, у которого или по отношению к которому что-то происходит, делается, указывается; обычно переводится дативом и/или генитивом с предлогом *у*_}}, quaedam [[subdūcuntur | #*sub-dūcere* -dūxisse -ductum# @take away (secretly or by stealth) / _похищать, отнимать, забирать (тайком, незаметно)_ ]], quaedam effluunt. Turpissima tamen est [[iactūra | #*iactūra* -ae ^f^# @throwing away; loss / _выбрасывание; потеря, утрата_]] quae per [[neglegentiam | #*neglegentia* -ae ^f^# [neglegēns] @carelessness, negligence, neglect / _невнимание, небрежность, пренебрежение_]] fit. Et sī {{volueris | _или_ *voluerīs*, _т. е._ indicativus (fut perf act) _или_ coniunctivus (perf act; casus potentialis); _так или иначе, здесь мыслится продолжение:_ *sī volueris attendere, vidēbis...*}} [[attendere | #*at-tendere* -tendisse -tentum# @direct attention, heed, mind, mark / _обращать внимание, внимать, замечать_]], magna pars vītae ēlābitur male agentibus, maxima nihil agentibus, tōta vīta aliud agentibus.

Quem mihi dabis quī aliquod pretium temporī {{pōnat | *pōnat* _и далее_ *aestimet*, *intellegat* – coniunctivus potentialis (praes act): _выражает возможное, потенциальное действие_}}, quī diem aestimet, quī intellegat sē cotīdiē morī? In hōc enim fallimur quod mortem prōspicimus: magna pars eius iam [[praeteriit | #*pareter-īre* -eō -iisse -itum# @go by, go past, pass / _проходить (мимо), миновать_ ¦ _cf.:_ tempus praeteritum]]; [[quidquid | #*quis-quis*, quid-quid# @whoever; whatever / _кто бы ни; что бы ни_ @*quidquid* + ^gen^ whatever, however much or many / _сколько бы ни_]] aetātis [[retrō | backwards; back, behind / _назад, обратно; (с, по)зади_]] est mors tenet. Fac ergō, mī Lūcīlī, quod {{facere | *quod facere tē scrībis* – acc cum inf}} tē scrībis: omnēs hōrās {{complectere | _у_ verba deponentia _императив на_ *-re* _(как будто инфинитив обычных глаголов)_}}; sīc fīet {{ut | *ut* explicativum @_поясняет, раскрывает содержание главного предложения с_ *fit*, *ēvenit* _и т. п. и требует сослагательного наклонения (coniunctivus); отсюда далее_ *pendeās*}} minus ex crāstinō [[pendeās | #*pendēre* pependisse# @1) hang (down), be suspended / _висеть, свисать_ @2) depend / _зависеть_]] sī hodiernō manum [[iniēcerīs | #*in-icere* -iēcisse -iectum# @throw in or on, cast over / _(в, на)брасывать, накидывать, налагать_ ¦ *manum inicere* lay one’s hand on, take hold of / _наложить руку на, завладеть_ @@*inēcerīs* – coniunctivus (prf act)]]. Dum [[differtur | #*dif-ferō* distulisse dīlātum# @1) carry apart, spread abroad, scatter, disperse / _разносить, распространять, рассеивать_ @2) putt off, delay / _откладывать, отсрочивать_]], vīta [[trānscurrit | #*trāns-currere* -(cu)currisse -cursum# @1) run across, pass through / _(пере, про)бегать_ @2) go by fast, elapse / _проходить, пролетать_]].

{{Omnia | *omnia aliēna* ^n pl^: субстантивированные прилагательные/местоимения, как и в РЯ, ставятся в латыни в сред. род, но, в отличие от РЯ, обычно во мн. число (_cf.:_ всё своё, большое и малое, чувство прекрасного)}}, Lūcīlī, aliēna sunt, tempus tantum nostrum est; in huius reī ūnīus [[fugācis | #*fugāx* -ācis# @swift, fleet, fleeting / _мимолётный, скоротечный_]] ac [[lūbricae | #*lūbricus* -a -um# @1) slippery / _скользкий_ @2) fleeting / _текучий, мимолётный_ @3) unsteady; inconstant / _шаткий; непостоянный_]] [[possessiōnem | #*possessiō* -ōnis ^f^# [possidēre] @possession, possessing / _обладание, владение_]] nātūra nōs mīsit, ex quā [[expellit | #*ex-pellere* -pulisse -pulsum# @expel, drive away, force out / _(вы, из, про)гонять_]] [[quīcumque | #*quī-cum-que* quae- quod-# @whosoever, whatsoever, everyone (-thing) that / _какой бы ни, всякий (кто)_]] vult. Et tanta stultitia mortālium est {{ut | *ut* consecutivum @_вводит придаточное следствия, которое ставится в сослагательном наклонении (coniunctivus)_: tanta est stultitia ut... *patiantur*}} quae minima et [[vīlissima | #*vīlis* -is# @cheap; of small value / _дешёвый; малоценный_]] sunt, certē [[reparābilia | #*reparābilis* -is# [reparāre] @raparable, retrievable / _поправимый, восстановимый; небезвозвратный_]], [[imputārī | #*im-putāre*# @reckon, charge; attribute / _засчитывать, ставить в счёт; приписывать, вменять_]] sibi cum [[impetrāvēre | #*im-petrāre*# @accomplish; obtain, procure (esp. by entreaty) / _добиться, достичь; (за)получить, выпросить_ @@*impetrāvēre* = impetrāvērunt]] [[patiantur | #*patī* -ior passum# @allow, let / _разрешать, позволять_]]; nēmō sē [[iūdicet | #*iūdicāre*# [iūdex] @1) judge, pass judgment / _судить; осуждать_ @2) judge (of), think / _иметь суждение, полагать_]] {{quicquam | = quid-quam}} dēbēre quī tempus accēpit, cum interim hoc ūnum est quod nē grātus quidem potest reddere.

Interrogābis fortasse quid ego {{faciam | coniunctivus в придаточных дополнительных, в косвенной речи: _cf._ – quid *facis*? _что ты делаешь?_ ↔ interrogō quid *faciās* _спрашиваю, что ты делаешь_}}, quī tibi {{ista | ^n pl^ < *istud*}} [[praecipiō | #*prae-cipere* -iō -cēpisse -ceptum# @1) give precepts, instruct, teach / _наставлять, учить, поучать_ @2) enjoin, direct, bid / _предписывать, велеть, отдавать распоряжение_]]. Fatēbor [[ingenuē | < *in-genuus* @frankly, ingenuously / _откровенно, чистосердечно, бесхитростно_]]: quod apud [[luxuriōsum | #*luxuriōsus* -a -um# [luxuria] @1) luxuriant; luxurious / _пышный; роскошный_ @2) extravagant / _расточительный_ @3) immoderate, excessive / _непомерный, чрезмерный_]] sed dīligentem [[ēvenit | #*ē-venīre* -vēnisse -ventum# @come to pass, happen, befall / _случаться, бывать, доводиться_]], [[ratiō | #*ratiō* -ōnis ^f^# @1) reckoning, account / _(под)счёт_ @2) matter, affair (esp. business) / _дела, отношения (особ. денежные)_ @3) relation / _отношение_ @4) regard, consideration / _учёт, соображение_]] mihi [[cōnstat | #*cōn-stāre* -stitisse -stātum# @be in agreement, correspond / _согласовываться, сходиться_ ¦ *ratiō cōnstat* the account is right / _счёт верен_]] [[impēnsae | #*im-pēnsa* -ae ^f^# @outlay, expense / _расход(ы), издержка_]]. Nōn possum {{dīcere | dīcere <*mē*> nihil perdere: _acc cum inf_}} nihil perdere, sed quid {{perdam | coniunctivus в придаточных дополнительных, в косвенной речи: см. выше под *faciam*}} et quārē et [[quemadmodum | *quem ad modum* @= quō modō]] — dīcam; causās paupertātis meae [[reddam | #*red-dere* -didisse -ditum# @declare, report, narrate / _излагать, рассказывать, передавать_]]. Sed ēvenit mihi quod plērīsque nōn suō [[vitiō | #*vitium* -ī ^n^# @vice, fault / _порок, изъян; погрешность; вина_]] ad [[inopiam | #*in-opia* -ae ^f^# @want, need; lack, scarcity / _нищета; неимение, недостаток_]] [[redāctīs | #*red-igere* -ēgisse -āctum# @1) drive back / _гнать назад, отгонять_ @2) reduce, render, make / _обращать, приводить (в к-л. состояние), доводить (до к-л. состояния)_]]: omnēs [[ignōscunt | #*ignōscere* -nōvisse -nōtum# @forgive, excuse, pardon / _прощать, извинять_]], nēmō [[succurrit | #*suc-currere* -currisse -cursum# @hasten to assistance, aid, succour / _спешить на помощь, приходить на выручку, помогать_]].

Quid ergō est? Nōn putō pauperem cui [[quantulumcumque | #*quantulus-cum-que* -a- -um-# @however small / _какой бы ни был маленький_]] superest [[sat | = satis]] est. Tū tamen [[mālō | #*mālle* māluisse# @prefer, choose rather / _предпочитать_]] servēs {{tua | ^n pl^}}, et bonō~tempore incipiēs. Nam ut vīsum~est [[maiōribus | #*maiōrēs* -um# ^m pl^ [maior] @1) elders / _старшие_ @2) ancestors, forefathers / _предки_]] nostrīs, “sēra [[parsimōnia | #*parsimōnia (parc-)* -ae ^f^# [parcere] @frugality, thrift / _бережливость_]] in [[fundō | #*fundus* -ī ^m^# @bottom / _дно_]] est”; nōn~enim tantum minimum in [[īmō | #*īmus* -a -um ^sup^# [īnfimus] @lowest, deepest / _самый нижний, глубинный_ @@#*īmum* -ī ^n^# @lowest part, bottom, depth / _нижняя часть, дно, глубина_]], sed pessimum [[remanet | #*re-manēre* -mānsisse -mānsum# @remain, be left / _оставаться_]]. Valē.

---

Сенека Луцилию своему привет~<шлет>

Так поступи мой Луцилий присвой себя себе и время которое до~сих~пор или отбиралось или похищалось или пропадало копи и береги Убедись <что>~дело так обстоит как пишу иное время отнимается у~нас иное незаметно~уводится иное утекает Позорнее~всего однако есть потеря которая по беспечности случается И ежели угодно~<тебе> обратить~внимание большáя часть жизни ускользает <у>~дурно делающих наибольшая <у>~ничего не~делающих вся жизнь <у>~иное делающих

Кого мне назовешь~(дашь) кто какую-то цену времени придавал~бы кто день ценил~бы кто понимал~бы <что>~он ежедневно умирает В том ведь ошибаемся что смерть прозреваем~впереди добрая часть ее уже прошла сколько~бы от~жизненной~поры позади ни~было смерть держит Делай же мой Луцилий что и~делаешь <как>~ты пишешь все часы обхвати так получится что меньше от завтрашнего будешь~зависеть если сегодняшнее в~руки возьмешь Пока откладывается жизнь проходит

Всё Луцилий чужое — время только наше — в этой вещью единственной скоротечной и ускользающей владение природа нас ввела из какового~<владения> изгоняет всякий~кто пожелает И такова глупость смертных — что то~что незначительно и малоценно — наверняка возместимо предъявлять~счет себе когда приобрели позволяют никто себя не~считает хоть~что-нибудь должным кто время получил когда меж~тем это единственное — что и благодарный даже не~может вернуть

Спросишь возможно что я́ делаю который тебя этому~вот поучает Призна́юсь прямодушно что у <человека>~расточительного но расчетливого бывает подсчет у~меня согласуется~с расходом Не могу сказать <что>~ничего не~теряю но что теряю и отчего и каким~образом скажу причины бедности моей изложу Но происходит со~мной что со~многими не по~своей вине до нищеты доведенными: все прощают, никто не~спешит~на~помощь

<Так>~что же — Не считаю бедным <того>~кому сколь~мало~бы ни~оставалось достаточно — Ты однако предпочитаю чтобы~берег твое~<состояние> и заблаговременно начнешь Ведь как представлялось предкам нашим запоздалая бережливость на дне — ибо~↔~не только крайне~малое в самом~низу но наихудшее остается Будь~здоров

---

Сенека приветствует Луцилия!

Так и поступай, мой Луцилий! Отвоюй себя для себя самого, береги и копи время, которое прежде у тебя отнимали или крали, которое зря проходило. Сам убедись в том, что я пишу правду: часть времени у нас отбирают силой, часть похищают, часть утекает впустую. Но позорнее всех потеря по нашей собственной небрежности. Вглядись-ка пристальней: ведь наибольшую часть жизни тратим мы на дурные дела, немалую — на безделье, и всю жизнь — не на те дела, что нужно.

Укажешь ли ты мне такого, кто ценил бы время, кто знал бы, чего стоит день, кто понимал бы, что умирает с каждым часом? В том-то и беда наша, что смерть мы видим впереди; а бо́льшая часть ее у нас за плечами, — ведь сколько лет жизни минуло, все принадлежат смерти. Поступай же так, мой Луцилий, как ты мне пишешь: не упускай ни часу. Удержишь в руках сегодняшний день — меньше будешь зависеть от завтрашнего. Не то, пока будешь откладывать, вся жизнь и промчится.

Всё у нас, Луцилий, чужое, одно лишь время наше. Только время, ускользающее и текучее, дала нам во владенье природа, но и его кто хочет, тот и отнимает. Смертные же глупы: получив что-нибудь ничтожное, дешевое и наверняка легко возместимое, они позволяют предъявлять себе счет; а вот те, кому уделили время, не считают себя должниками, хотя единственно времени и не возвратит даже знающий благодарность.

Быть может, ты спросишь, как поступаю я, если смею тебя поучать? Признаюсь чистосердечно: как расточитель, тщательный в подсчетах, я знаю, сколько растратил. Не могу сказать, что не теряю ничего, но сколько теряю, и почему, и как — скажу и назову причины моей бедности. Дело со мною обстоит так же, как с большинством тех, кто не через собственный порок дошел до нищеты: все меня прощают, никто не помогает.

Ну так что ж? По-моему, не беден тот, кому довольно и самого малого остатка. Но ты уж лучше береги свое достояние сейчас: ведь начать самое время! Как считали наши предки, поздно быть бережливым, когда осталось на донышке. Да к тому же остается там не только мало, но и самое скверное. Будь здоров.
  `
});
